[build-system]
requires = [
    "setuptools>=42",
    "oldest-supported-numpy; python_version < '3.9'",
    "numpy>=2.0.0; python_version >= '3.9'",
    "cython>=0.23"
]
build-backend = "setuptools.build_meta"
