#!/bin/bash


# remove comment 
sed -i "s/#'sphinx\_gallery/'sphinx\_gallery/" source/conf.py
sed -i "s/sys.modules.update/#sys.modules.update/" source/conf.py

make html

# put comment again 
sed -i "s/'sphinx\_gallery/#'sphinx\_gallery/" source/conf.py
sed -i "s/#sys.modules.update/sys.modules.update/" source/conf.py

#rsync --out-format="%n" --update  source/auto_examples/*.ipynb ../notebooks2
./nb_run_conv
