name: Build all wheels

on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * 1'
  push:
    branches:
      - "master"

jobs:
  build_wheels:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools

    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==2.16.2

    - name: Set up QEMU
      if: runner.os == 'Linux'
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all

    - name: Build wheels
      env:
        CIBW_SKIP: "pp*-win* pp*-macosx* cp2* pp* cp*musl* cp36* *i686" # remove pypy on mac and win (wrong version)
        CIBW_ARCHS_LINUX: auto aarch64 # force aarch64 with QEMU
        CIBW_ARCHS_MACOS: x86_64 universal2 arm64
      run: |
        python -m cibuildwheel --output-dir wheelhouse

    - uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ strategy.job-index }}
        path: ./wheelhouse
