name: Build all wheels

on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * 1'
  push:
    branches:
      - "master"
      
jobs:
  build_wheels:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -U "cython"

    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==1.10.0

    - name: Set up QEMU
      if: runner.os == 'Linux'
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all

    - name: Build wheels
      env:
        CIBW_SKIP: "pp*-win* pp*-macosx* cp2* pp*" # remove pypy on mac and win (wrong version)
        CIBW_BEFORE_BUILD: "pip install numpy cython"
        CIBW_ARCHS_LINUX: auto aarch64 # force aarch64 with QEMU
      run: |
        python -m cibuildwheel --output-dir wheelhouse

    - uses: actions/upload-artifact@v1
      with:
        name: wheels
        path: ./wheelhouse
