name: "Check updated RELEASES.md file"

on:
  pull_request:
    branches:
      - 'master'
jobs:
  check_release_file:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Verify Changed files
        uses: tj-actions/changed-files@v45
        id: changed-release-file
        with:
          files: 'RELEASES.md'
      - name: Check if RELEASES.md file is changed
        if: steps.changed-release-file.outputs.any_changed == 'false'
        run: exit 1
